name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get network config of runner
      run: |
          ifconfig
          ext_ip=$(curl ifconfig.me) && echo "Ext IP is $ext_ip"
          apt update && apt install whois
          whois "$ext_ip"
    
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag morkot/aws-cli:latest
    
    # - name: Logon to Dockerhub
    #   env:
    #     DOCKERHUB_PASSWORD: ${{ secrets. DOCKERHUB_PASSWORD}}
    #     DOCKERHUB_USERNAME: ${{ secrets. DOCKERHUB_USERNAME}}
    #   run: docker login --username morkot --password ${DOCKERHUB_PASSWORD}
    
    # - name: Push the Docker image
    #   run: docker push morkot/aws-cli:latest
    
    # - name: Docker Hub Description
    #   uses: peter-evans/dockerhub-description@v2.1.0
    #   env:
    #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    #     DOCKERHUB_REPOSITORY: morkot/aws-cli
